name: Checkout and Investigate Repo
on: workflow_dispatch

jobs:
  first-demo-job:
    runs-on: ubuntu-latest

    steps:
      - name: Install Tree
        run: sudo apt install tree -y
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Investigation Repo
        run: | 
          pwd
          tree -a
