name: Demo Github Actions
on: workflow_dispatch

jobs:
  first-demo-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Investigation Repo
        run: | 
          pwd
          ls -lart
