name: GitHub Actions On Push 
on: workflow_dispatch

jobs:
  clone-website-and-run-podman:
    runs-on: ubuntu-latest


    steps:
      - name: Git Clone Repo
        run: git clone https://github.com/Ryshai/Webdevpro
      - name: Check Website Files
        run: ls -lart /usr/share/nginx/html
      - name: Start And Enable
        run: |
          sudo systemctl enable nginx
          sudo systemctl start nginx 
      - name: Start nginx service
        run: sudo systemctl start nginx
      - name: Test web service 
        run: curl localhost:8080
        #python3 -c "import requests; r=requests.get(http://localhost:8080');print(r.status_code)"